### ISSUE TITLE
Error on preprocess cannot import StringIO

### ISSUE THREAD

**Issue by timjong93** [vene/marseille#3]
Hi,

I am looking into using your framework as a part of a tool i am developing as part of my thesis to asses the usability and credibility of whitepapers using internet information triangulation. One of the aspects, among other factors,  we are interested in is the amount of reasoning used in these whitepapers as an indicator for credibility.

I read your paper and it looked quite promissing, so i would like to try how it performs in our use case.
I am however running into some problems.

When trying to run the following command I get the error that the StringIO package cannot be imported. I did install all the requirements listed in the readme using pip. 
I am using a clean virtualenv running python 2.7.12 on ubuntu

`(marseille) ubuntu@ubuntu-xenial:/code/marseille$ python -m marseille.preprocess embeddings cdcp --glove-file=/p/glove.840B.300d.tx
t
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/code/marseille/marseille/preprocess.py", line 242, in <module>
    store_optimized_embeddings(dataset, args['--glove-file'])
  File "/code/marseille/marseille/preprocess.py", line 213, in store_optimized_embeddings
    from marseille.datasets import get_dataset_loader
  File "marseille/datasets.py", line 6, in <module>
    from marseille.argdoc import UkpEssayArgumentationDoc, CdcpArgumentationDoc
  File "marseille/argdoc.py", line 9, in <module>
    from io import StringIO
ImportError: cannot import name StringIO
(marseille) ubuntu@ubuntu-xenial:/code/marseille$`

I have the feeling that this is due to the io file which is part of the project, but i also assume that this file serves a purpose. So i am a bit lost at the moment.
Furtermore i noticed that the file structure in the downloaded dataset does not match the path as you describe it in the readme.

Any help would be greatly appreciated.
With kind regards,
Tim Jongsma

**Comment by vene** [comment]
In python2 the import path for stringio is different. Can you switch to python 3?

If not, I would welcome a pull request adding support for python 2.

**Comment by timjong93** [comment]
Sorry for the late response, got it working in the end by switching to python 3. 
Don't know why i didn't think of that -_-
Had some troubles installing the right dynet version, but now everything is working. Just need to install the dependencies to run my own datasets, i'm really curious about the results. Thanks for the help!
