### ISSUE TITLE
KeyError: 'collapsed-ccprocessed-dependencies'

### ISSUE THREAD

**Issue by timjong93** [vene/marseille#5]
Hi,

When trying to run the pretrained model on a custom document, i run into the following error.
Which i have not been able to solve. 

The command: 'python -m marseille.features user F'
Results in the following error: 
`Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/code/marseille/marseille/features.py", line 614, in <module>
    for prop_id in prop_ids]
  File "/code/marseille/marseille/features.py", line 614, in <listcomp>
    for prop_id in prop_ids]
  File "/code/marseille/marseille/features.py", line 205, in prop_features
    for arc in sents[sent]['collapsed-ccprocessed-dependencies']
KeyError: 'collapsed-ccprocessed-dependencies'`

For debug purposes i have tried replacing the custom document with one of the files from the cdcp dataset yielding the same error.

Any help would be appreciated,
With kind regards,
Tim

**Comment by vene** [comment]
The format of the Stanford corenlp output changed in newer versions. The missing key is there if you use version 3.6.0, as explained in marseille's readme.

Alternatively, a PR adding support to newer versions of Stanford corenlp is welcome!

**Comment by timjong93** [comment]
I thought i used 3.6.0, apparently i didn't. That does resolve the issue.
Now i'm running into issues where the process is randomly killed, seems like memory isues. 
Going to play around a bit more.
Thanks so far.
